### PR TITLE
Assert content available, add some content

### PR DESCRIPTION
**Pull request by maxjacobson**
👋  Hi @sivakumar-kailasam,

Just making a small update to help make sure builds don't fail when this check finds an issue. Example: https://codeclimate.com/github/Wolfsblvt/BlossomsPokemonGoManager/builds/397

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
oh thanks for the PR @maxjacobson.

**Comment by sivakumar-kailasam** [comment]
//cc @mrb

**Comment by sivakumar-kailasam** [comment]
Didn't realize you worked for codeclimate @maxjacobson 😄

**Comment by maxjacobson** [comment]
@sivakumar-kailasam yup! Thanks for merging, I'll get this onto the beta release today 😄 

Let me know if you'd like to work together on moving this engine from beta to stable... feel free to pop into the community slack if you'd like to talk through what the remaining steps are

**Comment by FernandoTBarros** [comment]
Oh Great! Thanks a lot for this "small update"! I was out of clue on getting this work! That was my commit who broke that build =/

**Pull request merged**
