### PR TITLE
scrape docs for correct checkstyle version

### PR DESCRIPTION
**Pull request by maxjacobson**
Belated follow-up to https://github.com/sivakumar-kailasam/codeclimate-checkstyle/pull/11#issuecomment-292675862

I'd like to confirm the circle build is green, and then ideally make it a required check going forward

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
@maxjacobson You would already have merge rights, feel free to merge your PRs 😉

**Comment by maxjacobson** [comment]
@sivakumar-kailasam ah, thanks, I didn't realize that 😅. WDYT about adding circle ci as a required check though?

**Comment by sivakumar-kailasam** [comment]
That sounds great. Enabled it,

screenshot 2017-04-19 21 01 22

**Comment by maxjacobson** [comment]
🎉 thanks. This is released

**Pull request merged**
