### PR TITLE
Rescrape docs to make build green

### PR DESCRIPTION
**Pull request by maxjacobson**
Once this is merged, we can release the 7.6 update

### CODE REVIEW

**Comment by maxjacobson** [comment]
@sivakumar-kailasam I think this looks good, but let me know if you have any concerns

**Comment by sivakumar-kailasam** [comment]
Lgtm

**Comment by sivakumar-kailasam** [comment]
@maxjacobson Made you a collaborator and enabled builds for forks.

**Comment by maxjacobson** [comment]
Sweet, thanks! The build sadly still isn't green, but maybe after #10? 🤞

**Pull request merged**
